name: .NET Build + Publish

on:
  push:
    branches: [ additional-connector-functionality ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet build --no-restore  --configuration Release -p:PostBuildEvent= 
    - name: Publish Windows 64bit
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet publish --os win --arch x64 -c Release -f net8.0 --self-contained false SnesConnectorApp/SnesConnectorApp.csproj
    - name: Publish Windows 32bit
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet publish --os win --arch x86 -c Release -f net8.0 --self-contained false SnesConnectorApp/SnesConnectorApp.csproj
    - name: Publish Linux 64bit
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet publish --os linux --arch x64 -c Release -f net8.0 --self-contained false SnesConnectorApp/SnesConnectorApp.csproj
    - name: Get version number
      if: ${{ github.event_name != 'pull_request' }}
      id: version
      run: |
        $version = (Get-Item "SnesConnectorApp\bin\Release\net8.0\win-x86\publish\SnesConnectorApp.exe").VersionInfo.ProductVersion
        $version = $version -replace "\+.*", ""
        Write-Output "number=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh
    - name: Copy Nuget Packages
      if: ${{ github.event_name != 'pull_request' }}
      shell: pwsh
      run: |
        Copy-Item -Path SnesConnectorLibrary\bin\Release\*.nupkg -Destination Output
    - name: Building the Linux 64bit package
      if: ${{ github.event_name != 'pull_request' }}
      shell: pwsh
      run: |
        $outputFile = "$pwd\Output\SnesConnectorApp_${{ steps.version.outputs.number }}.tar.gz"
        Set-Location SnesConnectorApp\bin\Release\net8.0\linux-x64\publish
        var -cvzf $outputFile *
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name != 'pull_request' }}
      with:
        path: "Output/*"
        name: SnesConnector_${{ steps.version.outputs.number }}
